# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gauravdave
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-api-http
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-api-http

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: GET
